// <auto-generated />
namespace EliteTrading.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class System_Locations_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(System_Locations_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201408220039275_System_Locations_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
