// <auto-generated />
namespace EliteTrading.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Factionsandserviesaddedtostations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Factionsandserviesaddedtostations));
        
        string IMigrationMetadata.Id
        {
            get { return "201505042214160_Factions-and-servies-added-to-stations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
