// <auto-generated />
namespace EliteTrading.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class renamednotificationtonews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamednotificationtonews));
        
        string IMigrationMetadata.Id
        {
            get { return "201501150805426_renamed-notification-to-news"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
