// <auto-generated />
namespace EliteTrading.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addedsupplydemandtocommoditiesremovedsomeoldstuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedsupplydemandtocommoditiesremovedsomeoldstuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201501140313017_added-supply-demand-to-commodities-removed-some-old-stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
