// <auto-generated />
namespace EliteTrading.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_systemid_to_EDDNLogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_systemid_to_EDDNLogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201512261404590_added_systemid_to_EDDNLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
